version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "monthly"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  groups:
    go-modules:
      patterns:
        - "*"
